//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        public Players()
        {
            this.Efectivo = 500D;
            this.Fichas = 0D;
            this.Victorias = 0;
            this.Jugadas = 0;
        }
    
        public int Id { get; set; }
        public string User { get; set; }
        public string Pass { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Email { get; set; }
        public double Efectivo { get; set; }
        public double Fichas { get; set; }
        public int Victorias { get; set; }
        public int Jugadas { get; set; }
        public int Avatar { get; set; }
    }
}
